[package]
name = "loteria_engine"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
rand = "0.8"

[dependencies.mlua]
version = "0.9"
features = ["lua54", "vendored"]

[lib]
name = "loteria_engine"
crate-type = ["cdylib", "rlib"]
