[package]
name = "loteria_engine"
version = "0.1.6"
edition = "2021"

[dependencies]
anyhow = "1.0"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
rand = "0.8"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"

[lib]
name = "loteria_engine"
crate-type = ["cdylib"]
